# Generated by Django 4.0.5 on 2022-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_wore_it_best', '0002_rename_people_vote_peoplevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplevote',
            name='vote',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
