# Generated by Django 4.0.5 on 2022-06-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_wore_it_best', '0003_alter_peoplevote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplevote',
            name='id',
        ),
        migrations.AlterField(
            model_name='peoplevote',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
